### ISSUE TITLE
Callback timed out, hook 'static:app.load' 

### ISSUE THREAD

**Issue by exomarty** [gmochi56/nodebb-plugin-watson#1]
Nice plugin,  i got the user created but  no working 
getting this error on load

![screenshot_8](https://user-images.githubusercontent.com/10746278/40089323-74f7afaa-58ab-11e8-83d5-8cce49a49e45.png)

and then this one

![screenshot_9](https://user-images.githubusercontent.com/10746278/40089365-aeab9c7a-58ab-11e8-84ce-c79fa23c68cf.png)

thank you

**Comment by GabrielMochi** [comment]
Thank you @exomarty!

This type of error is probably related to the credentials (username and password) or the workspace_id. Have you changed these values ​​in code?
- [username variable](https://github.com/GabrielMochi/nodebb-plugin-watson/blob/master/library.js#L21)
- [password variable](https://github.com/GabrielMochi/nodebb-plugin-watson/blob/master/library.js#L22)
- [workspace_id variable](https://github.com/GabrielMochi/nodebb-plugin-watson/blob/master/library.js#L57)

**Comment by exomarty** [comment]
I changed username and password but i dont where to find wordspace id on ibm website
Do i need to change something else?

**Comment by GabrielMochi** [comment]
This CURL command will return the workspace id

`curl -u "{username}":"{password}" "https://gateway.watsonplatform.net/conversation/api/v1/workspaces?version=2018-02-16"`

**Comment by exomarty** [comment]
nice, that command didnt work but i was able to create the workspace on ibm website
working now with demo workspace, thank you
however watson replies to every forum post , will be nice to able to invoke him with mention only

**Comment by GabrielMochi** [comment]
Good idea @exomarty! I left the watson responses as generic as possible, but it would even be interesting to implement a system where users could configure in which context watson should or should not respond.

Thank you for contacting me and providing solutions! Any other issues or concerns you may have, do not hesitate to contact me again.
